language: node_js
node_js:
  - "6"
before_script:
  - npm install -g bower
  - bower install
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: npm test
sudo: false
addons:
  firefox: "43.0"
